# Generated by Django 3.2.9 on 2021-11-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ngolist',
        ),
    ]
