# Generated by Django 3.2.9 on 2021-11-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0002_alter_ngolist_mobno'),
        ('Donate', '0003_ngolist'),
    ]

    operations = [
    ]
