# Generated by Django 3.2.9 on 2021-11-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donate', '0004_merge_0002_alter_ngolist_mobno_0003_ngolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngolist',
            name='ngo_email',
        ),
        migrations.RemoveField(
            model_name='ngolist',
            name='offwebsite',
        ),
        migrations.RemoveField(
            model_name='ngolist',
            name='year_founded',
        ),
        migrations.CreateModel(
            name='Ngoextra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
