# Generated by Django 3.2.9 on 2021-11-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0007_auto_20211124_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ngoextra',
        ),
    ]
