# Generated by Django 3.2.9 on 2021-11-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donate', '0008_delete_ngoextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngoextra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
