# Generated by Django 3.2.9 on 2021-11-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0009_ngoextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoextra',
            old_name='contact',
            new_name='mail_id',
        ),
    ]
