# Generated by Django 3.2.7 on 2021-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0013_alter_itemsdonated_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='type',
            field=models.CharField(choices=[('books', 'Books'), ('medicines', 'Medicines'), ('clothes', 'Clothes'), ('food', 'Food')], max_length=10),
        ),
    ]
