# Generated by Django 3.2.7 on 2021-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0014_alter_itemsdonated_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='ngoname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
