# Generated by Django 3.2.7 on 2021-11-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0015_alter_itemsdonated_ngoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='ngoname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donate.ngoextra'),
        ),
    ]
