# Generated by Django 3.2.7 on 2021-11-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0016_alter_itemsdonated_ngoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='ngoname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donate.ngoextra'),
        ),
    ]
