# Generated by Django 3.2.7 on 2021-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0019_itemsdonated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='status',
            field=models.CharField(choices=[('pickup confirmed', 'Pickup confirmed'), ('picked up', 'Picked up'), ('delivered', 'Delivered'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
