# Generated by Django 3.2.7 on 2021-11-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donate', '0020_alter_itemsdonated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdonated',
            name='ngoname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NGO', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsdonated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DONOR', to=settings.AUTH_USER_MODEL),
        ),
    ]
